### ISSUE TITLE
Unable to locate npm

### ISSUE THREAD

**Issue by aliahmad22** [KasRoudra/k-fuscator#1]
apt install git python -y && git clone https://github.com/KasRoudra/k-fuscator && cd k-fuscator && bash requirements.sh && python3 kf.py
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (2.36.1).
python is already the newest version (3.10.4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Cloning into 'k-fuscator'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 27 (delta 6), reused 25 (delta 4), pack-reused 0
Receiving objects: 100% (27/27), 1.60 MiB | 2.28 MiB/s, done.
Resolving deltas: 100% (6/6), done.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package npm
requirements.sh: line 2: npm: command not found

.... I have tried to install it manually also but again iam facing this problem help

**Comment by KasRoudra** [comment]
@aliahmad22 Do a `apt install nodejs -y`. Then run k-fuscator
