### ISSUE TITLE
CamHack

### ISSUE THREAD

**Issue by bahodirbuxorov** [KasRoudra/k-fuscator#2]
he takes a picture of the link and for some reason all the pictures are blacked out

**Comment by KasRoudra** [comment]
@Baxa073 what is the browser?

**Comment by bahodirbuxorov** [comment]
Chrome and Redmi browser

**Comment by KasRoudra** [comment]
@Baxa073 I'm not sure about readme but it works in chrome browser. Did you allow camera access?

**Comment by bahodirbuxorov** [comment]
Yes. But images black. I remembered it other phones. Maybe brauzer blocked it. Thanks for responding
